import { QueryResolvers } from '../../../generated/graphqlgen';
import axios from 'axios'


const Resolver: QueryResolvers.GetBankAccountNameResolver = async (_, { accountNo, bankCode }, ctx) => {



    const result = await axios.post<FlutterwaveAccountResponse>('https://api.flutterwave.com/v3/accounts/resolve', {
        account_bank: bankCode,
        account_number: accountNo
    } as FlutterwaveAccountPayload, {
        headers: {
            Authorization: 'Bearer ' + process.env.FLUTTERWAVE_SECRET
        }
    })

    return result.data.data.account_name

}

// Generated by https://quicktype.io

interface FlutterwaveAccountResponse {
    status: string;
    message: string;
    data: Data;
}

interface Data {
    account_number: string;
    account_name: string;
}

// Generated by https://quicktype.io

interface FlutterwaveAccountPayload {
    account_number: string;
    account_bank: string;
}


export default Resolver