import { QueryResolvers, MetaResolvers } from '../../../generated/graphqlgen';
import axios from 'axios'


const Meta: MetaResolvers.Type = {
    banks: async (parent, args, ctx) => {
        const result = await axios.get<FlutterwaveBanksResponse>('https://api.flutterwave.com/v3/banks/NG', {
            headers: {
                Authorization: 'Bearer ' + process.env.FLUTTERWAVE_SECRET
            }
        })
        return result.data.data
    }
};

// Generated by https://quicktype.io

interface FlutterwaveBanksResponse {
    status: string;
    message: string;
    data: Datum[];
}

interface Datum {
    id: number;
    code: string;
    name: string;
}


export default Meta
